In [165]:
import pandas as pd
import numpy as np

In [166]:
red = pd.read_csv('winequality-red.csv', delimiter=';')
red['type'] = 0
red.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [167]:
white = pd.read_csv('winequality-white.csv', delimiter=';')
white['type'] = 1
white.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,1
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,1
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,1
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,1
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,1

In [168]:
df = pd.concat([red,white],ignore_index=True)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [169]:
df.columns = [x.replace(' ','_') for x in df.columns] 
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [178]:
df.isnull().sum()

fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
type                    0
acidity                 0
dtype: int64

In [170]:
df.quality = df.quality.apply(lambda q: 'low' if q <= 5 else 'medium' if q <= 7 else 'high')

In [171]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df.quality = le.fit_transform(df.quality)

In [172]:
df['acidity'] = df['fixed_acidity'] + df['volatile_acidity'] + df['citric_acid']
df.drop(['fixed_acidity','volatile_acidity','citric_acid','free_sulfur_dioxide'], axis=1)

,residual_sugar,chlorides,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,type,acidity
0,1.90,0.076,34.0,0.99780,3.51,0.56,9.400000,1,0,8.100
1,2.60,0.098,67.0,0.99680,3.20,0.68,9.800000,1,0,8.680
2,2.30,0.092,54.0,0.99700,3.26,0.65,9.800000,1,0,8.600
3,1.90,0.075,60.0,0.99800,3.16,0.58,9.800000,2,0,12.040
4,1.90,0.076,34.0,0.99780,3.51,0.56,9.400000,1,0,8.100
5,1.80,0.075,40.0,0.99780,3.51,0.56,9.400000,1,0,8.060
6,1.60,0.069,59.0,0.99640,3.30,0.46,9.400000,1,0,8.560
7,1.20,0.065,21.0,0.99460,3.39,0.47,10.000000,2,0,7.950
8,2.00,0.073,18.0,0.99680,3.36,0.57,9.500000,2,0,8.400
9,6.10,0.071,102.0,0.99780,3.35,0.80,10.500000,1,0,8.360
10,1.80,0.097,65.0,0.99590,3.28,0.54,9.200000,1,0,7.360
11,6.10,0.071,102.0,0.99780,3.35,0.80,10.500000,1,0,8.360
12,1.60,0.089,59.0,0.99430,3.58,0.52,9.900000,1,0,6.215
13,1.60,0.114,29.0,0.99740,3.26,1.56,9.100000,1,0,8.700
14,3.80,0.176,145.0,0.99860,3.16,0.88,9.200000,1,0,9.700
15,3.90,0.170,148.0,0.99860,3.17,0.93,9.200000,1,0,9.710
16,1.80,0.092,103.0,0.99690,3.30,0.75,10.500000,2,0,9.340
17,1.70,0.368,56.0,0.99680,3.11,1.28,9.300000,1,0,8.940
18,4.40,0.086,29.0,0.99740,3.38,0.50,9.000000,1,0,8.070
19,1.80,0.341,56.0,0.99690,3.04,1.08,9.200000,2,0,8.730
20,1.80,0.077,60.0,0.99680,3.39,0.53,9.400000,2,0,9.600
21,2.30,0.082,71.0,0.99820,3.52,0.65,9.700000,1,0,8.300
22,1.60,0.106,37.0,0.99660,3.17,0.91,9.500000,1,0,8.540
23,2.30,0.084,67.0,0.99680,3.17,0.53,9.400000,1,0,9.100
24,2.40,0.085,40.0,0.99680,3.43,0.63,9.700000,2,0,7.440
25,1.40,0.080,23.0,0.99550,3.34,0.56,9.300000,1,0,6.850
26,1.80,0.080,11.0,0.99620,3.28,0.59,9.500000,1,0,8.250
27,1.60,0.106,37.0,0.99660,3.17,0.91,9.500000,1,0,8.540
28,1.90,0.080,35.0,0.99720,3.47,0.55,9.400000,1,0,7.810
29,2.00,0.082,16.0,0.99640,3.38,0.59,9.800000,2,0,8.445
...,...,...,...,...,...,...,...,...,...,...
6467,4.50,0.046,124.0,0.99324,3.31,0.64,10.800000,2,1,6.340
6468,10.10,0.032,81.0,0.99626,3.19,0.51,9.800000,2,1,7.170
6469,6.60,0.021,132.0,0.99188,3.15,0.36,11.450000,2,1,6.700
6470,1.90,0.015,98.0,0.98970,3.37,0.55,12.050000,2,1,5.600
6471,12.40,0.032,179.0,0.99622,3.14,0.60,9.700000,1,1,6.830
6472,1.60,0.030,122.0,0.99044,3.33,0.52,11.900000,2,1,6.230
6473,2.50,0.048,125.0,0.99282,3.49,0.49,10.000000,2,1,6.160
6474,1.20,0.035,97.0,0.99245,3.12,0.41,9.700000,2,1,7.880
6475,2.50,0.038,117.0,0.99132,3.36,0.59,11.600000,2,1,7.000
6476,0.80,0.032,82.0,0.99286,3.25,0.36,8.800000,1,1,6.440
6477,0.90,0.035,81.0,0.99234,3.24,0.35,9.500000,1,1,6.750
6478,8.10,0.046,170.0,0.99494,3.15,0.50,9.533333,2,1,7.340
6479,8.10,0.046,170.0,0.99494,3.15,0.50,9.533333,2,1,7.340
6480,11.75,0.030,118.0,0.99540,3.07,0.50,9.400000,2,1,5.505
6481,1.30,0.037,156.0,0.99184,3.26,0.38,10.700000,1,1,5.950
6482,1.90,0.035,148.0,0.98964,3.27,0.35,11.500000,2,1,5.540
6483,8.30,0.048,174.0,0.99492,3.14,0.50,9.600000,1,1,7.210
6484,8.10,0.046,170.0,0.99494,3.15,0.50,9.550000,2,1,7.340
6485,5.70,0.028,121.0,0.99168,3.21,1.08,12.150000,2,1,6.690
6486,1.90,0.023,56.0,0.98928,3.04,0.79,13.000000,2,1,6.830
6487,1.20,0.052,127.0,0.99330,3.04,0.54,9.200000,1,1,7.380
6488,11.75,0.030,118.0,0.99540,3.07,0.50,9.400000,2,1,5.405
6489,2.20,0.036,100.0,0.98938,3.06,0.44,11.800000,2,1,6.730
6490,0.90,0.038,121.0,0.99074,3.24,0.46,10.600000,2,1,6.230
6491,1.30,0.032,112.0,0.99298,3.29,0.54,9.700000,1,1,7.110
6492,1.60,0.039,92.0,0.99114,3.27,0.50,11.200000,2,1,6.700
6493,8.00,0.047,168.0,0.99490,3.15,0.46,9.600000,1,1,7.280
6494,1.20,0.041,111.0,0.99254,2.99,0.46,9.400000,2,1,6.930
6495,1.10,0.022,110.0,0.98869,3.34,0.38,12.800000,2,1,6.090
6496,0.80,0.020,98.0,0.98941,3.26,0.32,11.800000,2,1,6.590

In [173]:
X = df.loc[:, df.columns != 'quality'].values
y = df.quality.values

In [174]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [175]:
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB 
from sklearn.ensemble import RandomForestClassifier
from mlxtend.classifier import StackingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
import catboost as cb
import xgboost as xgb
import lightgbm as lgt

clf1 = RandomForestClassifier(n_estimators = 106, random_state=1)
clf2 = xgb.XGBClassifier(max_depth=50, min_child_weight=1,  n_estimators=200, n_jobs=-1 , verbose=1,learning_rate=0.16)
clf3 = SVR(kernel = 'rbf')
lr = LogisticRegression()


sclf = StackingClassifier(classifiers=[clf1, clf2, clf3], meta_classifier=lr)

sclf.fit(X_train,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

StackingClassifier(average_probas=False,
          classifiers=[RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_f...,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)],
          meta_classifier=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
          store_train_meta_features=False, use_clones=True,
          use_features_in_secondary=False, use_probas=False, verbose=0)

In [176]:
y_pred = sclf.predict(X_test)

In [177]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8023076923076923